name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build Docker Image
        run: docker build --no-cache -t ${{ secrets.DOCKERHUB_USERNAME }}/front .

      - name: Login Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_ID }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Image push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/front

  deploy:
    name: CD
    runs-on: ubuntu-latest
    permissions: write-all
    needs: build

    steps:
      - uses: actions/checkout@v3

      - name: Deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            sudo docker login -u ${{ secrets.DOCKERHUB_ID }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            sudo docker pull ${{secrets.DOCKERHUB_USERNAME}}/front
            sudo docker stop front
            sudo docker container rm front
            sudo docker run -dit -p 80:3000 --name front --restart always ${{secrets.DOCKERHUB_USERNAME}}/front
            sudo docker image prune -f